FROM node:20-bullseye-slim AS builder
WORKDIR /app

ARG NEXT_PUBLIC_APPLE_XML_PATH
ENV NEXT_PUBLIC_APPLE_XML_PATH=$NEXT_PUBLIC_APPLE_XML_PATH

COPY web/package.json .
RUN npm install
COPY ./web /app
RUN npm run build

FROM node:20-bullseye-slim
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json .

USER node

EXPOSE 3000
CMD ["npm", "start"]